### ISSUE TITLE
WinoMT dataset

### ISSUE THREAD

**Issue by Jiaxu-Zhao** [gabrielStanovsky/mt_gender#10]
Firstly, thanks for your attributions! i would like to ask that where could I dowmload the WinoMT dataset ? And the data/aggregates/en.txt, en_anti.txt, en_pro.txt are samples of WinoMT dataset?

**Comment by gabrielStanovsky** [comment]
Hi @zhao1402072392 , 
These are the corpus itself. `en.txt` is the full corpus, while `en_pro.txt` and `en_anti.txt` are two subsets of it, one for stereotypical gender role assignments and the other for anti-stereotypical.

**Comment by Jiaxu-Zhao** [comment]
> Hi @zhao1402072392 ,
> These are the corpus itself. `en.txt` is the full corpus, while `en_pro.txt` and `en_anti.txt` are two subsets of it, one for stereotypical gender role assignments and the other for anti-stereotypical.

got it, Thank you so much!
