### ISSUE TITLE
How to compute ΔS?

### ISSUE THREAD

**Issue by jvamvas** [gabrielStanovsky/mt_gender#11]
Thank you for providing this great resource!

Could you please shine some more light on how the difference in performance between the stereotypical and anti-stereotypical subsets (ΔS) is computed?

- Difference of F1 scores (description in the original paper); or
- Difference of accuracies (cf. https://github.com/gabrielStanovsky/mt_gender/blob/master/src/generate_table.py#L63)

**Comment by gabrielStanovsky** [comment]
Hi @jvamvas, 
I intended for ΔS to be the delta of *accuracies* as in the code. The paper version is an error, I'll fix that in future versions of the paper.

Thanks!

**Comment by jvamvas** [comment]
Thank you.
