### ISSUE TITLE
Human Validation

### ISSUE THREAD

**Issue by jvamvas** [gabrielStanovsky/mt_gender#12]
Would it be possible to share the data from the human validation in the original paper?

Creating 9600 annotations was surely a considerable effort, and sharing those data with the community could be of great value.

**Comment by gabrielStanovsky** [comment]
Hi @jvamvas, that's an excellent point.
I've started uploading them [here](https://github.com/gabrielStanovsky/mt_gender/tree/master/data/human_annotations).
I will work on finding all of the files and update them in that folder. I'll also work on documentation and add the annotation guidelines.
