### ISSUE TITLE
Tokenization

### ISSUE THREAD

**Issue by jvamvas** [gabrielStanovsky/mt_gender#13]
When evaluating with WinoMT, what is the recommended practice regarding tokenization?

Going through the reference implementation, it seems to me that the translations are _not_ supposed to be tokenized, but I am not entirely sure. Namely, it seems that the gender predictors expect a fast_align output that is based on untokenized text. Can you confirm this?

**Comment by gabrielStanovsky** [comment]
Hi @jvamvas , Yes, that's indeed the case, we do not tokenize the translations. 
The texts are rather simple, my intuition is that the difference between tokenized and untokenized text is not big.

**Comment by jvamvas** [comment]
Thank you for the reply.
