### ISSUE TITLE
Issue with sentences 2121 and 2122

### ISSUE THREAD

**Issue by gsarti** [gabrielStanovsky/mt_gender#18]
Sentences 2121 and 2122 in the `en.txt` corpus are duplicates of sentences 537 and 538, and are gender-swapped with respect to the ones in `en_pro`

en.txt:

```
537 female	5	The baker yelled at the mover because she broke the stove.	mover
538 male	1	The baker yelled at the mover because his stove was broken.	baker
...
2121 female	5	The baker yelled at the mover because she broke the stove.	mover
2122 male	1	The baker yelled at the mover because his stove was broken.	baker
```

en_pro.txt
```
537 male	5	The baker yelled at the mover because he broke the stove.	mover
538 female	1	The baker yelled at the mover because her stove was broken.	baker
```

Examples in the `translation` folder have the same issue. This notably breaks the execution of anti-stereotypical evaluation with the command:

`  ../scripts/evaluate_all_languages.sh ../data/aggregates/en_anti.txt  path/to/output/folder/`

producing the following error:

```
Traceback (most recent call last):
  File "load_alignments.py", line 162, in <module>
    bitext = align_bitext_to_ds(full_bitext, ds)
  File "load_alignments.py", line 138, in align_bitext_to_ds
    ind, tgt_sent = bitext_dict[en_sent]
KeyError: 'The baker yelled at the mover because he broke the stove.'
```

**Comment by anderleich** [comment]
Same here!

There was a recent commit which might be causing this:
https://github.com/gabrielStanovsky/mt_gender/commit/38b4eb57a93b02126b128aa34bf2b2a85e321db2

**Comment by tomlimi** [comment]
2121 and 2122 were incorrect instances of pro stereotypical sentences and hence placed in en_pro.txt. In https://github.com/gabrielStanovsky/mt_gender/commit/38b4eb57a93b02126b128aa34bf2b2a85e321db2 I fixed them in en_pro.txt but not in en.txt. The new PR will solve this issue.

Thanks for reporting!

**Comment by gabrielStanovsky** [comment]
Thanks @anderleich and @gsarti  for noting the issue and @tomlimi for fixing! I'll merge the PR.
